- name: install apt-transport-https software-properties-common wget certbot
  ansible.builtin.package:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
      - certbot
    state: present
  become: true

- name: create keyrings dir
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'
  become: true

- name: download grafana apt key
  ansible.builtin.shell: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
  become: true

- name: upload /etc/apt/sources.list.d/grafana.list to source
  ansible.builtin.copy:
    src: grafana.list
    dest: /etc/apt/sources.list.d/grafana.list
  become: true

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: install grafana
  ansible.builtin.package:
    name:
      - grafana
    state: present
  become: true


- name: Enable service grafana-server.service and ensure it is started
  ansible.builtin.systemd_service:
    name: grafana-server.service
    enabled: true
    state: started
  become: true
